name: WorkflowEjercicio1

on:
  push:
  pull_request:

jobs: 
  tareas:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar código
        uses: actions/checkout@v4


      - name: Preparar Python
        uses: actions/setup-python@v4

      - name: Instalar dependencias de Python
        run:
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ejecutar tests con pytest
        run:
          pytest
